/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

module fpmul(clk, in_ready, a, b, product, done);
  wire _000_;
  wire [5:0] _001_;
  wire [5:0] _002_;
  wire [3:0] _003_;
  wire [3:0] _004_;
  wire [10:0] _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire _380_;
  wire _381_;
  wire _382_;
  wire _383_;
  wire _384_;
  wire _385_;
  wire _386_;
  wire _387_;
  wire _388_;
  wire _389_;
  wire _390_;
  wire _391_;
  wire _392_;
  wire _393_;
  wire _394_;
  wire _395_;
  wire _396_;
  wire _397_;
  wire _398_;
  wire _399_;
  wire _400_;
  wire _401_;
  wire _402_;
  wire _403_;
  wire _404_;
  wire _405_;
  wire _406_;
  wire _407_;
  wire _408_;
  wire _409_;
  wire _410_;
  wire _411_;
  wire _412_;
  wire _413_;
  wire _414_;
  wire _415_;
  wire _416_;
  wire _417_;
  wire _418_;
  wire _419_;
  wire _420_;
  wire _421_;
  wire _422_;
  wire _423_;
  wire _424_;
  wire _425_;
  wire _426_;
  wire _427_;
  wire _428_;
  wire _429_;
  wire _430_;
  wire _431_;
  wire _432_;
  wire _433_;
  wire _434_;
  wire _435_;
  wire _436_;
  wire _437_;
  wire _438_;
  wire _439_;
  wire _440_;
  wire _441_;
  wire _442_;
  wire _443_;
  wire _444_;
  wire _445_;
  wire _446_;
  wire _447_;
  wire _448_;
  wire _449_;
  wire _450_;
  wire _451_;
  wire _452_;
  wire _453_;
  wire _454_;
  wire _455_;
  wire _456_;
  wire _457_;
  wire _458_;
  wire _459_;
  wire _460_;
  wire _461_;
  wire _462_;
  wire _463_;
  wire _464_;
  wire _465_;
  wire _466_;
  wire _467_;
  wire _468_;
  wire _469_;
  wire _470_;
  wire _471_;
  wire _472_;
  wire _473_;
  wire _474_;
  wire _475_;
  wire _476_;
  wire _477_;
  wire _478_;
  wire _479_;
  wire _480_;
  wire _481_;
  wire _482_;
  wire _483_;
  wire _484_;
  wire _485_;
  wire _486_;
  wire _487_;
  wire _488_;
  wire _489_;
  wire _490_;
  wire _491_;
  wire _492_;
  wire _493_;
  wire _494_;
  wire _495_;
  wire _496_;
  wire _497_;
  wire _498_;
  wire _499_;
  wire _500_;
  wire _501_;
  wire _502_;
  wire _503_;
  wire _504_;
  wire _505_;
  wire _506_;
  wire _507_;
  wire _508_;
  wire _509_;
  wire _510_;
  wire _511_;
  wire _512_;
  wire _513_;
  wire _514_;
  wire _515_;
  wire _516_;
  wire _517_;
  wire _518_;
  wire _519_;
  wire _520_;
  wire _521_;
  wire _522_;
  wire _523_;
  wire _524_;
  wire _525_;
  wire _526_;
  wire _527_;
  wire _528_;
  wire _529_;
  wire _530_;
  wire _531_;
  wire _532_;
  wire _533_;
  wire _534_;
  wire _535_;
  wire _536_;
  wire _537_;
  wire _538_;
  wire _539_;
  wire _540_;
  wire _541_;
  wire _542_;
  wire _543_;
  wire _544_;
  wire _545_;
  wire _546_;
  wire _547_;
  wire _548_;
  input [10:0] a;
  input [10:0] b;
  input clk;
  output done;
  reg done;
  reg [5:0] exp_a;
  reg [5:0] exp_b;
  input in_ready;
  reg [3:0] man_a;
  reg [3:0] man_b;
  output [10:0] product;
  reg [10:0] product;
  reg sign_a;
  reg sign_b;
  sky130_fd_sc_hd__clkinv_1 _549_ (
    .A(_526_),
    .Y(_541_)
  );
  sky130_fd_sc_hd__clkinv_1 _550_ (
    .A(_528_),
    .Y(_542_)
  );
  sky130_fd_sc_hd__clkinv_1 _551_ (
    .A(_529_),
    .Y(_543_)
  );
  sky130_fd_sc_hd__nand3_1 _552_ (
    .A(_541_),
    .B(_542_),
    .C(_543_),
    .Y(_544_)
  );
  sky130_fd_sc_hd__nor4_1 _553_ (
    .A(_499_),
    .B(_516_),
    .C(_522_),
    .D(_525_),
    .Y(_545_)
  );
  sky130_fd_sc_hd__nor4_1 _554_ (
    .A(_229_),
    .B(_424_),
    .C(_440_),
    .D(_484_),
    .Y(_546_)
  );
  sky130_fd_sc_hd__nand2_1 _555_ (
    .A(_545_),
    .B(_546_),
    .Y(_547_)
  );
  sky130_fd_sc_hd__clkinv_1 _556_ (
    .A(_230_),
    .Y(_548_)
  );
  sky130_fd_sc_hd__nor3_1 _557_ (
    .A(_324_),
    .B(_354_),
    .C(_369_),
    .Y(_231_)
  );
  sky130_fd_sc_hd__nor4_1 _558_ (
    .A(_240_),
    .B(_261_),
    .C(_272_),
    .D(_309_),
    .Y(_232_)
  );
  sky130_fd_sc_hd__nor3_1 _559_ (
    .A(_527_),
    .B(_537_),
    .C(_540_),
    .Y(_233_)
  );
  sky130_fd_sc_hd__nand4_1 _560_ (
    .A(_232_),
    .B(_548_),
    .C(_231_),
    .D(_233_),
    .Y(_234_)
  );
  sky130_fd_sc_hd__o21ai_0 _561_ (
    .A1(_544_),
    .A2(_547_),
    .B1(_234_),
    .Y(_235_)
  );
  sky130_fd_sc_hd__clkinv_1 _562_ (
    .A(_235_),
    .Y(_236_)
  );
  sky130_fd_sc_hd__nand2_1 _563_ (
    .A(_236_),
    .B(_353_),
    .Y(_237_)
  );
  sky130_fd_sc_hd__mux2_2 _564_ (
    .A0(_229_),
    .A1(_228_),
    .S(_237_),
    .X(_530_)
  );
  sky130_fd_sc_hd__clkinv_1 _565_ (
    .A(_353_),
    .Y(_238_)
  );
  sky130_fd_sc_hd__nand2_1 _566_ (
    .A(_238_),
    .B(_285_),
    .Y(_239_)
  );
  sky130_fd_sc_hd__clkinv_1 _567_ (
    .A(_538_),
    .Y(_241_)
  );
  sky130_fd_sc_hd__nand2_1 _568_ (
    .A(_531_),
    .B(_532_),
    .Y(_242_)
  );
  sky130_fd_sc_hd__nor2_1 _569_ (
    .A(_241_),
    .B(_242_),
    .Y(_243_)
  );
  sky130_fd_sc_hd__nand2_1 _570_ (
    .A(_532_),
    .B(_535_),
    .Y(_244_)
  );
  sky130_fd_sc_hd__clkinv_1 _571_ (
    .A(_244_),
    .Y(_245_)
  );
  sky130_fd_sc_hd__nor2_1 _572_ (
    .A(_245_),
    .B(_243_),
    .Y(_246_)
  );
  sky130_fd_sc_hd__clkinv_1 _573_ (
    .A(_534_),
    .Y(_247_)
  );
  sky130_fd_sc_hd__nand3_1 _574_ (
    .A(_531_),
    .B(_532_),
    .C(_533_),
    .Y(_248_)
  );
  sky130_fd_sc_hd__a21oi_1 _575_ (
    .A1(_531_),
    .A2(_532_),
    .B1(_533_),
    .Y(_249_)
  );
  sky130_fd_sc_hd__o21ai_0 _576_ (
    .A1(_247_),
    .A2(_249_),
    .B1(_248_),
    .Y(_250_)
  );
  sky130_fd_sc_hd__a21oi_1 _577_ (
    .A1(_532_),
    .A2(_538_),
    .B1(_531_),
    .Y(_251_)
  );
  sky130_fd_sc_hd__nor2_1 _578_ (
    .A(_251_),
    .B(_243_),
    .Y(_252_)
  );
  sky130_fd_sc_hd__nand2_1 _579_ (
    .A(_252_),
    .B(_250_),
    .Y(_253_)
  );
  sky130_fd_sc_hd__nand3b_1 _580_ (
    .A_N(_249_),
    .B(_534_),
    .C(_248_),
    .Y(_254_)
  );
  sky130_fd_sc_hd__o211ai_1 _581_ (
    .A1(_251_),
    .A2(_243_),
    .B1(_248_),
    .C1(_254_),
    .Y(_255_)
  );
  sky130_fd_sc_hd__nand3_1 _582_ (
    .A(_255_),
    .B(_536_),
    .C(_253_),
    .Y(_256_)
  );
  sky130_fd_sc_hd__nand2_1 _583_ (
    .A(_256_),
    .B(_253_),
    .Y(_257_)
  );
  sky130_fd_sc_hd__nand2_1 _584_ (
    .A(_242_),
    .B(_538_),
    .Y(_258_)
  );
  sky130_fd_sc_hd__xor2_1 _585_ (
    .A(_244_),
    .B(_258_),
    .X(_259_)
  );
  sky130_fd_sc_hd__maj3_1 _586_ (
    .A(_539_),
    .B(_257_),
    .C(_259_),
    .X(_260_)
  );
  sky130_fd_sc_hd__clkinv_1 _587_ (
    .A(_535_),
    .Y(_262_)
  );
  sky130_fd_sc_hd__clkinv_1 _588_ (
    .A(_531_),
    .Y(_263_)
  );
  sky130_fd_sc_hd__o21ai_0 _589_ (
    .A1(_263_),
    .A2(_241_),
    .B1(_532_),
    .Y(_264_)
  );
  sky130_fd_sc_hd__a22oi_1 _590_ (
    .A1(_245_),
    .A2(_241_),
    .B1(_264_),
    .B2(_262_),
    .Y(_265_)
  );
  sky130_fd_sc_hd__nand2_1 _591_ (
    .A(_260_),
    .B(_265_),
    .Y(_266_)
  );
  sky130_fd_sc_hd__xor2_1 _592_ (
    .A(_265_),
    .B(_260_),
    .X(_267_)
  );
  sky130_fd_sc_hd__nand2_1 _593_ (
    .A(_534_),
    .B(_535_),
    .Y(_268_)
  );
  sky130_fd_sc_hd__nor2_1 _594_ (
    .A(_268_),
    .B(_248_),
    .Y(_269_)
  );
  sky130_fd_sc_hd__clkinv_1 _595_ (
    .A(_269_),
    .Y(_270_)
  );
  sky130_fd_sc_hd__nand2_1 _596_ (
    .A(_535_),
    .B(_536_),
    .Y(_271_)
  );
  sky130_fd_sc_hd__nand4_1 _597_ (
    .A(_532_),
    .B(_533_),
    .C(_534_),
    .D(_535_),
    .Y(_273_)
  );
  sky130_fd_sc_hd__clkinv_1 _598_ (
    .A(_273_),
    .Y(_274_)
  );
  sky130_fd_sc_hd__and3_2 _599_ (
    .A(_531_),
    .B(_532_),
    .C(_533_),
    .X(_275_)
  );
  sky130_fd_sc_hd__o21bai_1 _600_ (
    .A1(_249_),
    .A2(_275_),
    .B1_N(_534_),
    .Y(_276_)
  );
  sky130_fd_sc_hd__a21oi_1 _601_ (
    .A1(_276_),
    .A2(_254_),
    .B1(_274_),
    .Y(_277_)
  );
  sky130_fd_sc_hd__o21ai_0 _602_ (
    .A1(_271_),
    .A2(_277_),
    .B1(_270_),
    .Y(_278_)
  );
  sky130_fd_sc_hd__a21oi_1 _603_ (
    .A1(_255_),
    .A2(_253_),
    .B1(_536_),
    .Y(_279_)
  );
  sky130_fd_sc_hd__nand3b_1 _604_ (
    .A_N(_279_),
    .B(_278_),
    .C(_256_),
    .Y(_280_)
  );
  sky130_fd_sc_hd__clkinv_1 _605_ (
    .A(_256_),
    .Y(_281_)
  );
  sky130_fd_sc_hd__clkinv_1 _606_ (
    .A(_271_),
    .Y(_282_)
  );
  sky130_fd_sc_hd__nand2_1 _607_ (
    .A(_532_),
    .B(_533_),
    .Y(_283_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _608_ (
    .A1_N(_254_),
    .A2_N(_276_),
    .B1(_283_),
    .B2(_268_),
    .Y(_284_)
  );
  sky130_fd_sc_hd__a21oi_1 _609_ (
    .A1(_284_),
    .A2(_282_),
    .B1(_269_),
    .Y(_286_)
  );
  sky130_fd_sc_hd__o21ai_0 _610_ (
    .A1(_279_),
    .A2(_281_),
    .B1(_286_),
    .Y(_287_)
  );
  sky130_fd_sc_hd__nand4_1 _611_ (
    .A(_287_),
    .B(_280_),
    .C(_535_),
    .D(_539_),
    .Y(_289_)
  );
  sky130_fd_sc_hd__xnor3_4 _612_ (
    .A(_539_),
    .B(_259_),
    .C(_257_),
    .X(_290_)
  );
  sky130_fd_sc_hd__a21oi_1 _613_ (
    .A1(_289_),
    .A2(_280_),
    .B1(_290_),
    .Y(_291_)
  );
  sky130_fd_sc_hd__clkinv_1 _614_ (
    .A(_291_),
    .Y(_292_)
  );
  sky130_fd_sc_hd__nand3_1 _615_ (
    .A(_290_),
    .B(_289_),
    .C(_280_),
    .Y(_293_)
  );
  sky130_fd_sc_hd__nand2_1 _616_ (
    .A(_292_),
    .B(_293_),
    .Y(_294_)
  );
  sky130_fd_sc_hd__nand3_1 _617_ (
    .A(_284_),
    .B(_270_),
    .C(_282_),
    .Y(_296_)
  );
  sky130_fd_sc_hd__nand2_1 _618_ (
    .A(_283_),
    .B(_268_),
    .Y(_297_)
  );
  sky130_fd_sc_hd__nand4_1 _619_ (
    .A(_297_),
    .B(_536_),
    .C(_538_),
    .D(_273_),
    .Y(_299_)
  );
  sky130_fd_sc_hd__clkinv_1 _620_ (
    .A(_299_),
    .Y(_300_)
  );
  sky130_fd_sc_hd__clkinv_1 _621_ (
    .A(_536_),
    .Y(_301_)
  );
  sky130_fd_sc_hd__o22ai_1 _622_ (
    .A1(_262_),
    .A2(_301_),
    .B1(_269_),
    .B2(_277_),
    .Y(_302_)
  );
  sky130_fd_sc_hd__nand3_1 _623_ (
    .A(_302_),
    .B(_296_),
    .C(_300_),
    .Y(_303_)
  );
  sky130_fd_sc_hd__clkinv_1 _624_ (
    .A(_539_),
    .Y(_305_)
  );
  sky130_fd_sc_hd__nor2_1 _625_ (
    .A(_241_),
    .B(_305_),
    .Y(_306_)
  );
  sky130_fd_sc_hd__nand2_1 _626_ (
    .A(_302_),
    .B(_296_),
    .Y(_308_)
  );
  sky130_fd_sc_hd__nand2_1 _627_ (
    .A(_308_),
    .B(_299_),
    .Y(_310_)
  );
  sky130_fd_sc_hd__nand3_1 _628_ (
    .A(_310_),
    .B(_303_),
    .C(_306_),
    .Y(_311_)
  );
  sky130_fd_sc_hd__nand2_1 _629_ (
    .A(_311_),
    .B(_303_),
    .Y(_313_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _630_ (
    .A1_N(_280_),
    .A2_N(_287_),
    .B1(_262_),
    .B2(_305_),
    .Y(_314_)
  );
  sky130_fd_sc_hd__nand3_1 _631_ (
    .A(_313_),
    .B(_314_),
    .C(_289_),
    .Y(_316_)
  );
  sky130_fd_sc_hd__clkinv_1 _632_ (
    .A(_316_),
    .Y(_317_)
  );
  sky130_fd_sc_hd__nor4_1 _633_ (
    .A(_263_),
    .B(_247_),
    .C(_301_),
    .D(_241_),
    .Y(_319_)
  );
  sky130_fd_sc_hd__nand2_1 _634_ (
    .A(_297_),
    .B(_273_),
    .Y(_321_)
  );
  sky130_fd_sc_hd__o21ai_0 _635_ (
    .A1(_301_),
    .A2(_241_),
    .B1(_321_),
    .Y(_322_)
  );
  sky130_fd_sc_hd__nand3_1 _636_ (
    .A(_322_),
    .B(_319_),
    .C(_299_),
    .Y(_323_)
  );
  sky130_fd_sc_hd__clkinv_1 _637_ (
    .A(_323_),
    .Y(_326_)
  );
  sky130_fd_sc_hd__a21oi_1 _638_ (
    .A1(_322_),
    .A2(_299_),
    .B1(_319_),
    .Y(_327_)
  );
  sky130_fd_sc_hd__nor2_1 _639_ (
    .A(_327_),
    .B(_326_),
    .Y(_329_)
  );
  sky130_fd_sc_hd__nand3_1 _640_ (
    .A(_329_),
    .B(_531_),
    .C(_539_),
    .Y(_331_)
  );
  sky130_fd_sc_hd__nand2_1 _641_ (
    .A(_331_),
    .B(_323_),
    .Y(_333_)
  );
  sky130_fd_sc_hd__and3_2 _642_ (
    .A(_302_),
    .B(_296_),
    .C(_300_),
    .X(_334_)
  );
  sky130_fd_sc_hd__a21oi_1 _643_ (
    .A1(_302_),
    .A2(_296_),
    .B1(_300_),
    .Y(_335_)
  );
  sky130_fd_sc_hd__o22ai_1 _644_ (
    .A1(_241_),
    .A2(_305_),
    .B1(_335_),
    .B2(_334_),
    .Y(_336_)
  );
  sky130_fd_sc_hd__nand3_1 _645_ (
    .A(_336_),
    .B(_311_),
    .C(_333_),
    .Y(_337_)
  );
  sky130_fd_sc_hd__or2b_2 _646_ (
    .A(_327_),
    .B_N(_323_),
    .X(_338_)
  );
  sky130_fd_sc_hd__o21ai_0 _647_ (
    .A1(_263_),
    .A2(_305_),
    .B1(_338_),
    .Y(_339_)
  );
  sky130_fd_sc_hd__nand2_1 _648_ (
    .A(_531_),
    .B(_536_),
    .Y(_341_)
  );
  sky130_fd_sc_hd__nand2_1 _649_ (
    .A(_534_),
    .B(_538_),
    .Y(_342_)
  );
  sky130_fd_sc_hd__a21oi_1 _650_ (
    .A1(_241_),
    .A2(_534_),
    .B1(_539_),
    .Y(_344_)
  );
  sky130_fd_sc_hd__a21oi_1 _651_ (
    .A1(_341_),
    .A2(_342_),
    .B1(_344_),
    .Y(_346_)
  );
  sky130_fd_sc_hd__nand4_1 _652_ (
    .A(_339_),
    .B(_331_),
    .C(_533_),
    .D(_346_),
    .Y(_348_)
  );
  sky130_fd_sc_hd__a21oi_1 _653_ (
    .A1(_336_),
    .A2(_311_),
    .B1(_333_),
    .Y(_349_)
  );
  sky130_fd_sc_hd__o21ai_0 _654_ (
    .A1(_348_),
    .A2(_349_),
    .B1(_337_),
    .Y(_350_)
  );
  sky130_fd_sc_hd__a21oi_1 _655_ (
    .A1(_310_),
    .A2(_306_),
    .B1(_334_),
    .Y(_351_)
  );
  sky130_fd_sc_hd__nand2_1 _656_ (
    .A(_314_),
    .B(_289_),
    .Y(_352_)
  );
  sky130_fd_sc_hd__nand2_1 _657_ (
    .A(_352_),
    .B(_351_),
    .Y(_355_)
  );
  sky130_fd_sc_hd__a21oi_1 _658_ (
    .A1(_350_),
    .A2(_355_),
    .B1(_317_),
    .Y(_356_)
  );
  sky130_fd_sc_hd__o21ai_0 _659_ (
    .A1(_294_),
    .A2(_356_),
    .B1(_292_),
    .Y(_357_)
  );
  sky130_fd_sc_hd__nand2_1 _660_ (
    .A(_357_),
    .B(_267_),
    .Y(_358_)
  );
  sky130_fd_sc_hd__nand3_1 _661_ (
    .A(_358_),
    .B(_246_),
    .C(_266_),
    .Y(_359_)
  );
  sky130_fd_sc_hd__clkinv_1 _662_ (
    .A(_333_),
    .Y(_361_)
  );
  sky130_fd_sc_hd__xor3_4 _663_ (
    .A(_300_),
    .B(_306_),
    .C(_308_),
    .X(_362_)
  );
  sky130_fd_sc_hd__nand2_1 _664_ (
    .A(_362_),
    .B(_361_),
    .Y(_364_)
  );
  sky130_fd_sc_hd__nand2_1 _665_ (
    .A(_364_),
    .B(_337_),
    .Y(_366_)
  );
  sky130_fd_sc_hd__xor2_1 _666_ (
    .A(_348_),
    .B(_366_),
    .X(_368_)
  );
  sky130_fd_sc_hd__nor3_1 _667_ (
    .A(_263_),
    .B(_305_),
    .C(_338_),
    .Y(_370_)
  );
  sky130_fd_sc_hd__o211a_1 _668_ (
    .A1(_326_),
    .A2(_370_),
    .B1(_311_),
    .C1(_336_),
    .X(_371_)
  );
  sky130_fd_sc_hd__clkinv_1 _669_ (
    .A(_348_),
    .Y(_372_)
  );
  sky130_fd_sc_hd__a21oi_1 _670_ (
    .A1(_364_),
    .A2(_372_),
    .B1(_371_),
    .Y(_373_)
  );
  sky130_fd_sc_hd__nand2_1 _671_ (
    .A(_355_),
    .B(_316_),
    .Y(_374_)
  );
  sky130_fd_sc_hd__xnor2_1 _672_ (
    .A(_374_),
    .B(_373_),
    .Y(_375_)
  );
  sky130_fd_sc_hd__a21oi_1 _673_ (
    .A1(_359_),
    .A2(_375_),
    .B1(_238_),
    .Y(_376_)
  );
  sky130_fd_sc_hd__o21ai_0 _674_ (
    .A1(_359_),
    .A2(_368_),
    .B1(_376_),
    .Y(_377_)
  );
  sky130_fd_sc_hd__a21oi_1 _675_ (
    .A1(_377_),
    .A2(_239_),
    .B1(_235_),
    .Y(_288_)
  );
  sky130_fd_sc_hd__clkinv_1 _676_ (
    .A(_359_),
    .Y(_379_)
  );
  sky130_fd_sc_hd__nand2_1 _677_ (
    .A(_379_),
    .B(_375_),
    .Y(_380_)
  );
  sky130_fd_sc_hd__o21bai_1 _678_ (
    .A1(_374_),
    .A2(_373_),
    .B1_N(_317_),
    .Y(_382_)
  );
  sky130_fd_sc_hd__xor2_1 _679_ (
    .A(_294_),
    .B(_382_),
    .X(_384_)
  );
  sky130_fd_sc_hd__a21oi_1 _680_ (
    .A1(_359_),
    .A2(_384_),
    .B1(_238_),
    .Y(_386_)
  );
  sky130_fd_sc_hd__a22oi_1 _681_ (
    .A1(_238_),
    .A2(_295_),
    .B1(_380_),
    .B2(_386_),
    .Y(_387_)
  );
  sky130_fd_sc_hd__nor2_1 _682_ (
    .A(_235_),
    .B(_387_),
    .Y(_298_)
  );
  sky130_fd_sc_hd__nand2_1 _683_ (
    .A(_238_),
    .B(_304_),
    .Y(_388_)
  );
  sky130_fd_sc_hd__clkinv_1 _684_ (
    .A(_267_),
    .Y(_389_)
  );
  sky130_fd_sc_hd__a21oi_1 _685_ (
    .A1(_382_),
    .A2(_293_),
    .B1(_291_),
    .Y(_390_)
  );
  sky130_fd_sc_hd__xor2_1 _686_ (
    .A(_389_),
    .B(_390_),
    .X(_391_)
  );
  sky130_fd_sc_hd__nand2_1 _687_ (
    .A(_379_),
    .B(_384_),
    .Y(_392_)
  );
  sky130_fd_sc_hd__o211ai_1 _688_ (
    .A1(_391_),
    .A2(_379_),
    .B1(_353_),
    .C1(_392_),
    .Y(_393_)
  );
  sky130_fd_sc_hd__a21oi_1 _689_ (
    .A1(_393_),
    .A2(_388_),
    .B1(_235_),
    .Y(_307_)
  );
  sky130_fd_sc_hd__nand2_1 _690_ (
    .A(_379_),
    .B(_391_),
    .Y(_394_)
  );
  sky130_fd_sc_hd__clkinv_1 _691_ (
    .A(_246_),
    .Y(_395_)
  );
  sky130_fd_sc_hd__nand2_1 _692_ (
    .A(_358_),
    .B(_266_),
    .Y(_396_)
  );
  sky130_fd_sc_hd__a21oi_1 _693_ (
    .A1(_396_),
    .A2(_395_),
    .B1(_238_),
    .Y(_397_)
  );
  sky130_fd_sc_hd__o21ai_0 _694_ (
    .A1(_353_),
    .A2(_312_),
    .B1(_236_),
    .Y(_398_)
  );
  sky130_fd_sc_hd__a21oi_1 _695_ (
    .A1(_394_),
    .A2(_397_),
    .B1(_398_),
    .Y(_315_)
  );
  sky130_fd_sc_hd__xor2_1 _696_ (
    .A(_318_),
    .B(_320_),
    .X(_399_)
  );
  sky130_fd_sc_hd__clkinv_1 _697_ (
    .A(_399_),
    .Y(_400_)
  );
  sky130_fd_sc_hd__nand4_1 _698_ (
    .A(_358_),
    .B(_246_),
    .C(_266_),
    .D(_400_),
    .Y(_401_)
  );
  sky130_fd_sc_hd__a21oi_1 _699_ (
    .A1(_359_),
    .A2(_399_),
    .B1(_238_),
    .Y(_402_)
  );
  sky130_fd_sc_hd__o21ai_0 _700_ (
    .A1(_353_),
    .A2(_325_),
    .B1(_236_),
    .Y(_404_)
  );
  sky130_fd_sc_hd__a21oi_1 _701_ (
    .A1(_402_),
    .A2(_401_),
    .B1(_404_),
    .Y(_328_)
  );
  sky130_fd_sc_hd__nand2_1 _702_ (
    .A(_318_),
    .B(_320_),
    .Y(_406_)
  );
  sky130_fd_sc_hd__nor2_1 _703_ (
    .A(_330_),
    .B(_332_),
    .Y(_408_)
  );
  sky130_fd_sc_hd__clkinv_1 _704_ (
    .A(_408_),
    .Y(_410_)
  );
  sky130_fd_sc_hd__nand2_1 _705_ (
    .A(_330_),
    .B(_332_),
    .Y(_411_)
  );
  sky130_fd_sc_hd__nand2_1 _706_ (
    .A(_410_),
    .B(_411_),
    .Y(_412_)
  );
  sky130_fd_sc_hd__clkinv_1 _707_ (
    .A(_412_),
    .Y(_413_)
  );
  sky130_fd_sc_hd__nand2_1 _708_ (
    .A(_413_),
    .B(_406_),
    .Y(_414_)
  );
  sky130_fd_sc_hd__nor2_1 _709_ (
    .A(_406_),
    .B(_413_),
    .Y(_415_)
  );
  sky130_fd_sc_hd__clkinv_1 _710_ (
    .A(_415_),
    .Y(_416_)
  );
  sky130_fd_sc_hd__nand2_1 _711_ (
    .A(_416_),
    .B(_414_),
    .Y(_417_)
  );
  sky130_fd_sc_hd__clkinv_1 _712_ (
    .A(_417_),
    .Y(_418_)
  );
  sky130_fd_sc_hd__nand2_1 _713_ (
    .A(_401_),
    .B(_418_),
    .Y(_419_)
  );
  sky130_fd_sc_hd__nor2_1 _714_ (
    .A(_418_),
    .B(_401_),
    .Y(_420_)
  );
  sky130_fd_sc_hd__nor2_1 _715_ (
    .A(_238_),
    .B(_420_),
    .Y(_422_)
  );
  sky130_fd_sc_hd__o21ai_0 _716_ (
    .A1(_353_),
    .A2(_340_),
    .B1(_236_),
    .Y(_423_)
  );
  sky130_fd_sc_hd__a21oi_1 _717_ (
    .A1(_422_),
    .A2(_419_),
    .B1(_423_),
    .Y(_343_)
  );
  sky130_fd_sc_hd__nor2_1 _718_ (
    .A(_345_),
    .B(_347_),
    .Y(_427_)
  );
  sky130_fd_sc_hd__nand2_1 _719_ (
    .A(_345_),
    .B(_347_),
    .Y(_428_)
  );
  sky130_fd_sc_hd__clkinv_1 _720_ (
    .A(_428_),
    .Y(_430_)
  );
  sky130_fd_sc_hd__nor2_1 _721_ (
    .A(_427_),
    .B(_430_),
    .Y(_431_)
  );
  sky130_fd_sc_hd__xor2_1 _722_ (
    .A(_410_),
    .B(_431_),
    .X(_433_)
  );
  sky130_fd_sc_hd__nor2_1 _723_ (
    .A(_415_),
    .B(_433_),
    .Y(_434_)
  );
  sky130_fd_sc_hd__nand2_1 _724_ (
    .A(_433_),
    .B(_415_),
    .Y(_436_)
  );
  sky130_fd_sc_hd__clkinv_1 _725_ (
    .A(_436_),
    .Y(_437_)
  );
  sky130_fd_sc_hd__nor2_1 _726_ (
    .A(_434_),
    .B(_437_),
    .Y(_439_)
  );
  sky130_fd_sc_hd__o21ai_0 _727_ (
    .A1(_418_),
    .A2(_401_),
    .B1(_439_),
    .Y(_441_)
  );
  sky130_fd_sc_hd__clkinv_1 _728_ (
    .A(_439_),
    .Y(_443_)
  );
  sky130_fd_sc_hd__nand2_1 _729_ (
    .A(_420_),
    .B(_443_),
    .Y(_444_)
  );
  sky130_fd_sc_hd__o21ai_0 _730_ (
    .A1(_353_),
    .A2(_360_),
    .B1(_236_),
    .Y(_446_)
  );
  sky130_fd_sc_hd__a31oi_1 _731_ (
    .A1(_444_),
    .A2(_353_),
    .A3(_441_),
    .B1(_446_),
    .Y(_363_)
  );
  sky130_fd_sc_hd__o31ai_1 _732_ (
    .A1(_408_),
    .A2(_427_),
    .A3(_430_),
    .B1(_436_),
    .Y(_448_)
  );
  sky130_fd_sc_hd__nor2_1 _733_ (
    .A(_365_),
    .B(_367_),
    .Y(_449_)
  );
  sky130_fd_sc_hd__nand2_1 _734_ (
    .A(_365_),
    .B(_367_),
    .Y(_451_)
  );
  sky130_fd_sc_hd__clkinv_1 _735_ (
    .A(_451_),
    .Y(_452_)
  );
  sky130_fd_sc_hd__nor2_1 _736_ (
    .A(_449_),
    .B(_452_),
    .Y(_454_)
  );
  sky130_fd_sc_hd__xor2_1 _737_ (
    .A(_430_),
    .B(_454_),
    .X(_455_)
  );
  sky130_fd_sc_hd__nand2_1 _738_ (
    .A(_448_),
    .B(_455_),
    .Y(_457_)
  );
  sky130_fd_sc_hd__clkinv_1 _739_ (
    .A(_457_),
    .Y(_458_)
  );
  sky130_fd_sc_hd__nor2_1 _740_ (
    .A(_455_),
    .B(_448_),
    .Y(_460_)
  );
  sky130_fd_sc_hd__nor2_1 _741_ (
    .A(_460_),
    .B(_458_),
    .Y(_461_)
  );
  sky130_fd_sc_hd__nand2_1 _742_ (
    .A(_444_),
    .B(_461_),
    .Y(_463_)
  );
  sky130_fd_sc_hd__o2111a_1 _743_ (
    .A1(_389_),
    .A2(_390_),
    .B1(_246_),
    .C1(_266_),
    .D1(_400_),
    .X(_464_)
  );
  sky130_fd_sc_hd__clkinv_1 _744_ (
    .A(_461_),
    .Y(_466_)
  );
  sky130_fd_sc_hd__nand4_1 _745_ (
    .A(_464_),
    .B(_417_),
    .C(_443_),
    .D(_466_),
    .Y(_467_)
  );
  sky130_fd_sc_hd__o21ai_0 _746_ (
    .A1(_353_),
    .A2(_378_),
    .B1(_236_),
    .Y(_469_)
  );
  sky130_fd_sc_hd__a31oi_1 _747_ (
    .A1(_463_),
    .A2(_353_),
    .A3(_467_),
    .B1(_469_),
    .Y(_381_)
  );
  sky130_fd_sc_hd__o31ai_1 _748_ (
    .A1(_428_),
    .A2(_449_),
    .A3(_452_),
    .B1(_457_),
    .Y(_471_)
  );
  sky130_fd_sc_hd__nor2_1 _749_ (
    .A(_383_),
    .B(_385_),
    .Y(_472_)
  );
  sky130_fd_sc_hd__nand2_1 _750_ (
    .A(_383_),
    .B(_385_),
    .Y(_474_)
  );
  sky130_fd_sc_hd__clkinv_1 _751_ (
    .A(_474_),
    .Y(_475_)
  );
  sky130_fd_sc_hd__nor2_1 _752_ (
    .A(_472_),
    .B(_475_),
    .Y(_477_)
  );
  sky130_fd_sc_hd__xor2_1 _753_ (
    .A(_452_),
    .B(_477_),
    .X(_478_)
  );
  sky130_fd_sc_hd__nand2_1 _754_ (
    .A(_471_),
    .B(_478_),
    .Y(_480_)
  );
  sky130_fd_sc_hd__clkinv_1 _755_ (
    .A(_480_),
    .Y(_481_)
  );
  sky130_fd_sc_hd__nor2_1 _756_ (
    .A(_478_),
    .B(_471_),
    .Y(_483_)
  );
  sky130_fd_sc_hd__nor2_1 _757_ (
    .A(_483_),
    .B(_481_),
    .Y(_485_)
  );
  sky130_fd_sc_hd__nand2_1 _758_ (
    .A(_467_),
    .B(_485_),
    .Y(_487_)
  );
  sky130_fd_sc_hd__nor3_1 _759_ (
    .A(_418_),
    .B(_439_),
    .C(_401_),
    .Y(_488_)
  );
  sky130_fd_sc_hd__clkinv_1 _760_ (
    .A(_485_),
    .Y(_490_)
  );
  sky130_fd_sc_hd__nand3_1 _761_ (
    .A(_488_),
    .B(_466_),
    .C(_490_),
    .Y(_491_)
  );
  sky130_fd_sc_hd__o21ai_0 _762_ (
    .A1(_353_),
    .A2(_403_),
    .B1(_236_),
    .Y(_493_)
  );
  sky130_fd_sc_hd__a31oi_1 _763_ (
    .A1(_487_),
    .A2(_491_),
    .A3(_353_),
    .B1(_493_),
    .Y(_405_)
  );
  sky130_fd_sc_hd__clkinv_1 _764_ (
    .A(_477_),
    .Y(_495_)
  );
  sky130_fd_sc_hd__o21ai_0 _765_ (
    .A1(_451_),
    .A2(_495_),
    .B1(_480_),
    .Y(_497_)
  );
  sky130_fd_sc_hd__xnor2_1 _766_ (
    .A(_407_),
    .B(_409_),
    .Y(_498_)
  );
  sky130_fd_sc_hd__xor2_1 _767_ (
    .A(_475_),
    .B(_498_),
    .X(_501_)
  );
  sky130_fd_sc_hd__clkinv_1 _768_ (
    .A(_501_),
    .Y(_502_)
  );
  sky130_fd_sc_hd__nor2_1 _769_ (
    .A(_502_),
    .B(_497_),
    .Y(_503_)
  );
  sky130_fd_sc_hd__clkinv_1 _770_ (
    .A(_497_),
    .Y(_504_)
  );
  sky130_fd_sc_hd__nor2_1 _771_ (
    .A(_501_),
    .B(_504_),
    .Y(_505_)
  );
  sky130_fd_sc_hd__nor2_1 _772_ (
    .A(_503_),
    .B(_505_),
    .Y(_506_)
  );
  sky130_fd_sc_hd__nand4_1 _773_ (
    .A(_488_),
    .B(_466_),
    .C(_490_),
    .D(_506_),
    .Y(_507_)
  );
  sky130_fd_sc_hd__o22ai_1 _774_ (
    .A1(_503_),
    .A2(_505_),
    .B1(_485_),
    .B2(_467_),
    .Y(_508_)
  );
  sky130_fd_sc_hd__o21ai_0 _775_ (
    .A1(_353_),
    .A2(_421_),
    .B1(_236_),
    .Y(_509_)
  );
  sky130_fd_sc_hd__a31oi_1 _776_ (
    .A1(_508_),
    .A2(_353_),
    .A3(_507_),
    .B1(_509_),
    .Y(_425_)
  );
  sky130_fd_sc_hd__nand2_1 _777_ (
    .A(_228_),
    .B(_426_),
    .Y(_510_)
  );
  sky130_fd_sc_hd__nor2_1 _778_ (
    .A(_228_),
    .B(_426_),
    .Y(_511_)
  );
  sky130_fd_sc_hd__nand3b_1 _779_ (
    .A_N(_511_),
    .B(_353_),
    .C(_510_),
    .Y(_512_)
  );
  sky130_fd_sc_hd__nand2_1 _780_ (
    .A(_238_),
    .B(_429_),
    .Y(_513_)
  );
  sky130_fd_sc_hd__a21oi_1 _781_ (
    .A1(_512_),
    .A2(_513_),
    .B1(_235_),
    .Y(_432_)
  );
  sky130_fd_sc_hd__mux2_2 _782_ (
    .A0(_527_),
    .A1(_426_),
    .S(_237_),
    .X(_435_)
  );
  sky130_fd_sc_hd__nand2_1 _783_ (
    .A(_237_),
    .B(_534_),
    .Y(_514_)
  );
  sky130_fd_sc_hd__o21ai_0 _784_ (
    .A1(_541_),
    .A2(_237_),
    .B1(_514_),
    .Y(_438_)
  );
  sky130_fd_sc_hd__nor2_1 _785_ (
    .A(_525_),
    .B(_237_),
    .Y(_515_)
  );
  sky130_fd_sc_hd__a21oi_1 _786_ (
    .A1(_301_),
    .A2(_237_),
    .B1(_515_),
    .Y(_442_)
  );
  sky130_fd_sc_hd__nand2_1 _787_ (
    .A(_237_),
    .B(_539_),
    .Y(_517_)
  );
  sky130_fd_sc_hd__o21ai_0 _788_ (
    .A1(_543_),
    .A2(_237_),
    .B1(_517_),
    .Y(_445_)
  );
  sky130_fd_sc_hd__nand2_1 _789_ (
    .A(_237_),
    .B(_532_),
    .Y(_518_)
  );
  sky130_fd_sc_hd__o21ai_0 _790_ (
    .A1(_542_),
    .A2(_237_),
    .B1(_518_),
    .Y(_447_)
  );
  sky130_fd_sc_hd__mux2_2 _791_ (
    .A0(_324_),
    .A1(_533_),
    .S(_237_),
    .X(_450_)
  );
  sky130_fd_sc_hd__nor2_1 _792_ (
    .A(_309_),
    .B(_237_),
    .Y(_519_)
  );
  sky130_fd_sc_hd__a21oi_1 _793_ (
    .A1(_263_),
    .A2(_237_),
    .B1(_519_),
    .Y(_453_)
  );
  sky130_fd_sc_hd__nor2_1 _794_ (
    .A(_369_),
    .B(_237_),
    .Y(_520_)
  );
  sky130_fd_sc_hd__a21oi_1 _795_ (
    .A1(_241_),
    .A2(_237_),
    .B1(_520_),
    .Y(_456_)
  );
  sky130_fd_sc_hd__nor2_1 _796_ (
    .A(_354_),
    .B(_237_),
    .Y(_521_)
  );
  sky130_fd_sc_hd__a21oi_1 _797_ (
    .A1(_262_),
    .A2(_237_),
    .B1(_521_),
    .Y(_459_)
  );
  sky130_fd_sc_hd__mux2_2 _798_ (
    .A0(_499_),
    .A1(_320_),
    .S(_237_),
    .X(_462_)
  );
  sky130_fd_sc_hd__mux2_2 _799_ (
    .A0(_484_),
    .A1(_332_),
    .S(_237_),
    .X(_465_)
  );
  sky130_fd_sc_hd__mux2_2 _800_ (
    .A0(_522_),
    .A1(_347_),
    .S(_237_),
    .X(_468_)
  );
  sky130_fd_sc_hd__mux2_2 _801_ (
    .A0(_516_),
    .A1(_367_),
    .S(_237_),
    .X(_470_)
  );
  sky130_fd_sc_hd__mux2_2 _802_ (
    .A0(_440_),
    .A1(_385_),
    .S(_237_),
    .X(_473_)
  );
  sky130_fd_sc_hd__mux2_2 _803_ (
    .A0(_424_),
    .A1(_409_),
    .S(_237_),
    .X(_476_)
  );
  sky130_fd_sc_hd__mux2_2 _804_ (
    .A0(_240_),
    .A1(_318_),
    .S(_237_),
    .X(_479_)
  );
  sky130_fd_sc_hd__nand2_1 _805_ (
    .A(_237_),
    .B(_330_),
    .Y(_523_)
  );
  sky130_fd_sc_hd__o21ai_0 _806_ (
    .A1(_548_),
    .A2(_237_),
    .B1(_523_),
    .Y(_482_)
  );
  sky130_fd_sc_hd__mux2_2 _807_ (
    .A0(_272_),
    .A1(_345_),
    .S(_237_),
    .X(_486_)
  );
  sky130_fd_sc_hd__mux2_2 _808_ (
    .A0(_261_),
    .A1(_365_),
    .S(_237_),
    .X(_489_)
  );
  sky130_fd_sc_hd__mux2_2 _809_ (
    .A0(_540_),
    .A1(_383_),
    .S(_237_),
    .X(_492_)
  );
  sky130_fd_sc_hd__mux2_2 _810_ (
    .A0(_537_),
    .A1(_407_),
    .S(_237_),
    .X(_494_)
  );
  sky130_fd_sc_hd__nor2_1 _811_ (
    .A(_353_),
    .B(_496_),
    .Y(_524_)
  );
  sky130_fd_sc_hd__nand2_1 _812_ (
    .A(_236_),
    .B(_524_),
    .Y(_500_)
  );
  always @(posedge clk)
      product[0] <= _005_[0];
  always @(posedge clk)
      product[1] <= _005_[1];
  always @(posedge clk)
      product[2] <= _005_[2];
  always @(posedge clk)
      product[3] <= _005_[3];
  always @(posedge clk)
      product[4] <= _005_[4];
  always @(posedge clk)
      product[5] <= _005_[5];
  always @(posedge clk)
      product[6] <= _005_[6];
  always @(posedge clk)
      product[7] <= _005_[7];
  always @(posedge clk)
      product[8] <= _005_[8];
  always @(posedge clk)
      product[9] <= _005_[9];
  always @(posedge clk)
      product[10] <= _005_[10];
  always @(posedge clk)
      done <= _000_;
  always @(posedge clk)
      sign_a <= _006_;
  always @(posedge clk)
      sign_b <= _007_;
  always @(posedge clk)
      exp_a[0] <= _001_[0];
  always @(posedge clk)
      exp_a[1] <= _001_[1];
  always @(posedge clk)
      exp_a[2] <= _001_[2];
  always @(posedge clk)
      exp_a[3] <= _001_[3];
  always @(posedge clk)
      exp_a[4] <= _001_[4];
  always @(posedge clk)
      exp_a[5] <= _001_[5];
  always @(posedge clk)
      exp_b[0] <= _002_[0];
  always @(posedge clk)
      exp_b[1] <= _002_[1];
  always @(posedge clk)
      exp_b[2] <= _002_[2];
  always @(posedge clk)
      exp_b[3] <= _002_[3];
  always @(posedge clk)
      exp_b[4] <= _002_[4];
  always @(posedge clk)
      exp_b[5] <= _002_[5];
  always @(posedge clk)
      man_a[0] <= _003_[0];
  always @(posedge clk)
      man_a[1] <= _003_[1];
  always @(posedge clk)
      man_a[2] <= _003_[2];
  always @(posedge clk)
      man_a[3] <= _003_[3];
  always @(posedge clk)
      man_b[0] <= _004_[0];
  always @(posedge clk)
      man_b[1] <= _004_[1];
  always @(posedge clk)
      man_b[2] <= _004_[2];
  always @(posedge clk)
      man_b[3] <= _004_[3];
  assign _228_ = sign_b;
  assign _229_ = b[10];
  assign _353_ = in_ready;
  assign _527_ = a[10];
  assign _537_ = a[9];
  assign _540_ = a[8];
  assign _230_ = a[5];
  assign _240_ = a[4];
  assign _261_ = a[7];
  assign _272_ = a[6];
  assign _309_ = a[1];
  assign _324_ = a[0];
  assign _354_ = a[3];
  assign _369_ = a[2];
  assign _424_ = b[9];
  assign _440_ = b[8];
  assign _484_ = b[5];
  assign _499_ = b[4];
  assign _516_ = b[7];
  assign _522_ = b[6];
  assign _525_ = b[1];
  assign _526_ = b[0];
  assign _528_ = b[3];
  assign _529_ = b[2];
  assign _007_ = _530_;
  assign _531_ = man_a[1];
  assign _532_ = man_b[3];
  assign _533_ = man_a[0];
  assign _534_ = man_b[0];
  assign _535_ = man_a[3];
  assign _536_ = man_b[1];
  assign _538_ = man_a[2];
  assign _539_ = man_b[2];
  assign _285_ = product[0];
  assign _005_[0] = _288_;
  assign _295_ = product[1];
  assign _005_[1] = _298_;
  assign _304_ = product[2];
  assign _005_[2] = _307_;
  assign _312_ = product[3];
  assign _005_[3] = _315_;
  assign _318_ = exp_a[0];
  assign _320_ = exp_b[0];
  assign _325_ = product[4];
  assign _005_[4] = _328_;
  assign _330_ = exp_a[1];
  assign _332_ = exp_b[1];
  assign _340_ = product[5];
  assign _005_[5] = _343_;
  assign _345_ = exp_a[2];
  assign _347_ = exp_b[2];
  assign _360_ = product[6];
  assign _005_[6] = _363_;
  assign _365_ = exp_a[3];
  assign _367_ = exp_b[3];
  assign _378_ = product[7];
  assign _005_[7] = _381_;
  assign _383_ = exp_a[4];
  assign _385_ = exp_b[4];
  assign _403_ = product[8];
  assign _005_[8] = _405_;
  assign _407_ = exp_a[5];
  assign _409_ = exp_b[5];
  assign _421_ = product[9];
  assign _005_[9] = _425_;
  assign _426_ = sign_a;
  assign _429_ = product[10];
  assign _005_[10] = _432_;
  assign _006_ = _435_;
  assign _004_[0] = _438_;
  assign _004_[1] = _442_;
  assign _004_[2] = _445_;
  assign _004_[3] = _447_;
  assign _003_[0] = _450_;
  assign _003_[1] = _453_;
  assign _003_[2] = _456_;
  assign _003_[3] = _459_;
  assign _002_[0] = _462_;
  assign _002_[1] = _465_;
  assign _002_[2] = _468_;
  assign _002_[3] = _470_;
  assign _002_[4] = _473_;
  assign _002_[5] = _476_;
  assign _001_[0] = _479_;
  assign _001_[1] = _482_;
  assign _001_[2] = _486_;
  assign _001_[3] = _489_;
  assign _001_[4] = _492_;
  assign _001_[5] = _494_;
  assign _496_ = done;
  assign _000_ = _500_;
endmodule
